name: flutter_ecommerce_app
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  flutter_platform_widgets: ^3.3.4
  device_preview: ^1.1.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  qr_code_scanner: ^1.0.1
  flutter_typeahead: ^4.6.0
  google_maps_flutter: ^2.2.8
  firebase_core:
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  carousel_slider: ^4.2.1
  filter_list: ^1.0.2
  curved_navigation_bar: ^1.0.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  permission_handler: ^10.3.0
  line_awesome_flutter: ^2.0.0
  country_picker: ^2.0.20
  shared_preferences: ^2.1.2
  encrypt: ^5.0.1
  photo_view: ^0.14.0
  flutter_dialogs: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
      - images/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
          weight: 700  
